### PR TITLE
Blog index canonicals

### PR DESCRIPTION
**Pull request by crumb1e**
Get the correct blog index url including query string and set it as the canonical.

### CODE REVIEW

**Review by m2de — COMMENTED** [review]
Hey @crumb1e . Actually, I think this line is left over from an early version. We don't want the blog to be coupled to the Pages module in any way, so we should in-fact remove the `with('page')` completely?

**Comment by crumb1e** [comment]
@m2de removed the `with('page')` !!

**Review by m2de — APPROVED** [review]

**Comment by m2de** [comment]
@crumb1e What's happening with this PR?

**Comment by crumb1e** [comment]
@m2de Not sure, it kinda got lost in the ether 😅 do we still need this?

**Pull request closed without merging**
